name 'springnet'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures springnet'
long_description 'Installs/Configures springnet'
version '0.1.0'
